/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public configuration (Keycloak realm/client) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.KeycloakModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a public club invitation by token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invitation token */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubInvitationPublicDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/invitations/{token}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set password and complete a public invitation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invitation token */
                    token: string;
                };
                cookie?: never;
            };
            /** @description Completion payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ClubInvitationCompleteDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/users/{userId}/{image}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public access to a user's profile image */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                    /** @description Image identifier */
                    image: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List authors for the current user */
        get: {
            parameters: {
                query: {
                    /** @description Page index (0-based) */
                    page: number;
                    /** @description Optional name filter */
                    name?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.PagedAuthorRepresentationModelList"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an author */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description New author payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.AuthorCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Author"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authors/{authorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an author */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author ID */
                    authorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update an author */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author ID */
                    authorId: string;
                };
                cookie?: never;
            };
            /** @description Author patch payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.AuthorPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Author"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/authors/{authorId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notes belonging to an author */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author ID */
                    authorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Note"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new club (with the current user as admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Club payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ClubPostDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{clubId}/me/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's permissions inside a club */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubPermissionsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{clubId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members of a club */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubMemberDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{clubId}/members/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download club members as CSV */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{clubId}/members/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite club members from a CSV upload (multipart "file") */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubInviteResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{clubId}/members/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite users by email to a club */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                };
                cookie?: never;
            };
            /** @description Email payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ClubInvitePostDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubInviteResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{clubId}/members/{memberUserId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a club member's role */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                    /** @description Member user ID */
                    memberUserId: string;
                };
                cookie?: never;
            };
            /** @description Role payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ClubMemberRolePatchDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/v1/clubs/{clubId}/messages/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members who can be chatted with */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubMessageCandidateDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{clubId}/messages/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's chats in a club */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubChatSummaryDto"][];
                    };
                };
            };
        };
        put?: never;
        /** Start a new chat with a recipient */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                };
                cookie?: never;
            };
            /** @description New chat payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ClubChatCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubChatCreatedDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{clubId}/messages/chats/{chatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages in a chat */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                    /** @description Chat ID */
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubChatMessageDto"][];
                    };
                };
            };
        };
        put?: never;
        /** Append a message to a chat */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Club ID */
                    clubId: string;
                    /** @description Chat ID */
                    chatId: string;
                };
                cookie?: never;
            };
            /** @description Message payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ClubChatPostMessageDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clubs the current user belongs to */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClubDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/concerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List concerts for the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ConcertDto"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a new concert */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Concert payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ConcertPostDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ConcertDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/concerts/{concertId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single concert */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Concert ID */
                    concertId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ConcertDto"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a concert */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Concert ID */
                    concertId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elements/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search folders (paginated) */
        get: {
            parameters: {
                query: {
                    /** @description Page index (0-based) */
                    page: number;
                    /** @description Folder name filter */
                    folderName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.PagedFolderRepresentationModelList"];
                    };
                };
            };
        };
        put?: never;
        /** Create a folder */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Folder payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.FolderPostDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Folder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elements/folders/{folderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a folder */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder ID */
                    folderId: string;
                };
                cookie?: never;
            };
            /** @description Patch payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.FolderPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Folder"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/elements/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated list of notes for the current user */
        get: {
            parameters: {
                query?: {
                    /** @description Page index (0-based) */
                    page?: number;
                    /** @description Optional name filter */
                    noteName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.PagedNoteRepresentationModelList"];
                    };
                };
            };
        };
        put?: never;
        /** Create a note */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["dto.NotePostDto"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Note"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elements/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a note plus prev/next siblings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Note ID */
                    noteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.NoteDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a note */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Note ID */
                    noteId: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["dto.NotePostDto"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Note"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/elements/parentDecks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all top-level folders for the user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Folder"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elements/{elementid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a folder or note by id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Element ID */
                    elementid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elements/{firstElement}/{lastElement}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Move an element to a different parent */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Element ID to move */
                    firstElement: string;
                    /** @description Target parent ID */
                    lastElement: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/v1/elements/{folderId}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List children (folders + notes) of a folder */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Parent folder ID */
                    folderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elements/{folderId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate a combined PDF for all notes in a folder */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder ID */
                    folderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elements/{noteId}/parent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the parent folder ID of a note */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Note ID */
                    noteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elements/{noteId}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the PDF attached to a note */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Note ID */
                    noteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
            };
        };
        put?: never;
        /** Replace the PDF for a note (raw body) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Note ID */
                    noteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Note"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events for a user since a given date */
        get: {
            parameters: {
                query?: {
                    /** @description Earliest event date (RFC3339) */
                    since?: string;
                };
                header?: never;
                path: {
                    /** @description User ID (must match authenticated user) */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Event"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticated accept of a club invitation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invitation token */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Sync the authenticated user from Keycloak claims (creates if missing) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk download of all folders, authors and notes for offline use */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user (by token) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.User"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user's profile fields */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                };
                cookie?: never;
            };
            /** @description User patch payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UserPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.User"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/users/{userId}/konzertmeister-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the configured Konzertmeister iCal URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.IcalSyncDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Save the Konzertmeister iCal URL */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                };
                cookie?: never;
            };
            /** @description iCal URL payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.IcalSyncDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.IcalSyncDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}/konzertmeister-url/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger iCal sync for the configured Konzertmeister URL */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: number;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a profile picture (raw image body) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.User"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        /** Delete the profile picture of a user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.User"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "dto.Author": {
            extraInformation: string;
            id: string;
            name: string;
        };
        "dto.AuthorCreateDto": {
            extraInformation: string;
            name: string;
        };
        "dto.AuthorPatchDto": {
            extraInformation: string;
            name: string;
        };
        "dto.ClubChatCreateDto": {
            content: string;
            recipient_user_id: string;
        };
        "dto.ClubChatCreatedDto": {
            chat_id: string;
        };
        "dto.ClubChatMessageDto": {
            chat_id: string;
            content: string;
            created_at: string;
            id: string;
            sender_display_name: string;
            sender_email: string;
            sender_user_id: string;
        };
        "dto.ClubChatPostMessageDto": {
            content: string;
        };
        "dto.ClubChatSummaryDto": {
            chat_id: string;
            club_id: string;
            last_message: string;
            last_message_at: string;
            last_sender_user_id: string;
            other_display_name: string;
            other_email: string;
            other_user_id: string;
        };
        "dto.ClubDto": {
            club_type: string;
            confirmed_representative: boolean;
            country: string;
            dates_visible_for_all_members: boolean;
            feedback_visibility: string;
            house_number: string;
            id: string;
            location: string;
            members_can_send_messages: boolean;
            name: string;
            postal_code: string;
            reason_visibility: string;
            street: string;
        };
        "dto.ClubInvitationCompleteDto": {
            confirm_password: string;
            firstname: string;
            lastname: string;
            password: string;
        };
        "dto.ClubInvitationPublicDto": {
            club_id: string;
            club_name: string;
            expires_at: string;
            invited_email: string;
            is_accepted: boolean;
            is_expired: boolean;
            token: string;
        };
        "dto.ClubInvitePostDto": {
            emails: string[];
        };
        "dto.ClubInviteResultDto": {
            added_emails: string[];
            failed_emails: string[];
            invited_emails: string[];
        };
        "dto.ClubMemberDto": {
            email: string;
            firstname: string;
            lastname: string;
            role: string;
            user_id: string;
            username: string;
        };
        "dto.ClubMemberRolePatchDto": {
            role: string;
        };
        "dto.ClubMessageCandidateDto": {
            display_name: string;
            email: string;
            user_id: string;
        };
        "dto.ClubPermissionsDto": {
            can_invite_members: boolean;
            can_manage_roles: boolean;
            role: string;
            section_write: {
                [key: string]: boolean;
            };
        };
        "dto.ClubPostDto": {
            club_type: string;
            confirmed_representative: boolean;
            country: string;
            dates_visible_for_all_members: boolean;
            feedback_visibility: string;
            house_number: string;
            location: string;
            members_can_send_messages: boolean;
            name: string;
            postal_code: string;
            reason_visibility: string;
            street: string;
        };
        "dto.ConcertDto": {
            description: string;
            dueDate: string;
            hints: string;
            id: string;
            location: string;
            noteInConcerts: components["schemas"]["dto.NoteInConcertDto"][];
            title: string;
        };
        "dto.ConcertPostDto": {
            description: string;
            dueDate: string;
            hints: string;
            location: string;
            title: string;
        };
        "dto.Event": {
            description?: string;
            endDate?: string;
            geoDateX?: number;
            geoDateY?: number;
            location?: string;
            startDate?: string;
            status: number;
            summary: string;
            tzId?: string;
            uid: string;
            url: string;
        };
        "dto.Folder": {
            creationDate: string;
            creator: components["schemas"]["dto.User"];
            description: string;
            id: string;
            name: string;
            parent?: components["schemas"]["dto.Folder"];
            /** @enum {string} */
            type: "folder";
        };
        "dto.FolderPatchDto": {
            description: string;
            name: string;
            parentId?: string;
        };
        "dto.FolderPostDto": {
            description: string;
            name: string;
            parentId?: string;
        };
        "dto.IcalSyncDto": {
            id: string;
            url: string;
        };
        "dto.KeycloakModel": {
            clientId: string;
            realm: string;
            url: string;
        };
        "dto.Note": {
            author: components["schemas"]["dto.Author"];
            creationDate: string;
            creator: components["schemas"]["dto.User"];
            description: string;
            id: string;
            name: string;
            numberOfPages: number;
            parent?: components["schemas"]["dto.Folder"];
            pdfAvailable: boolean;
            /** @enum {string} */
            type: "note";
        };
        "dto.NoteDetailResponse": {
            currentNote?: components["schemas"]["dto.Note"];
            index: number;
            nextNote?: components["schemas"]["dto.Note"];
            previousNote?: components["schemas"]["dto.Note"];
        };
        "dto.NoteInConcertDto": {
            noteInConcert: components["schemas"]["dto.Note"];
            placeInConcert: number;
        };
        "dto.NotePostDto": {
            authorId: string;
            description: string;
            name: string;
            numberOfPages: number;
            parentId: string;
            pdfContent?: string;
        };
        "dto.Page": {
            number: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        "dto.PagedAuthorRepresentationModelList": {
            _embedded: {
                authorRepresentationModelList: components["schemas"]["dto.Author"][];
            };
            page: components["schemas"]["dto.Page"];
        };
        "dto.PagedFolderRepresentationModelList": {
            _embedded: {
                elementRepresentationModelList: components["schemas"]["dto.Folder"][];
            };
            page: components["schemas"]["dto.Page"];
        };
        "dto.PagedNoteRepresentationModelList": {
            _embedded: {
                noteRepresentationModelList: components["schemas"]["dto.Note"][];
            };
            page: components["schemas"]["dto.Page"];
        };
        "dto.User": {
            email: string;
            firstname: string;
            lastname: string;
            profilePicUrl?: string;
            sideBarCollapsed: boolean;
            telephoneNumber: string;
            userId: string;
            username: string;
        };
        "dto.UserPatchDto": {
            email: string;
            firstname: string;
            lastname: string;
            sideBarCollapsed: boolean;
            telephoneNumber: string;
            username: string;
        };
        "models.Author": {
            extraInformation?: string;
            id?: string;
            name?: string;
            user?: components["schemas"]["models.User"];
        };
        "models.Folder": {
            creationDate?: string;
            creator?: components["schemas"]["models.User"];
            description?: string;
            elements?: unknown[];
            id?: string;
            name?: string;
            parent?: components["schemas"]["models.Folder"];
        };
        "models.Note": {
            author?: components["schemas"]["models.Author"];
            creationDate?: string;
            creator?: components["schemas"]["models.User"];
            description?: string;
            id?: string;
            name?: string;
            numberOfPages?: number;
            parent?: components["schemas"]["models.Folder"];
            pdfAvailable?: boolean;
            pdfContent?: number[];
        };
        "models.User": {
            email?: string;
            firstname?: string;
            lastname?: string;
            profilePicUrl?: number[];
            sideBarCollapsed?: boolean;
            telephoneNumber?: string;
            userId?: string;
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description Note payload */
        "dto.NotePostDto": {
            content: {
                "application/json": components["schemas"]["dto.NotePostDto"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
