image: maven:latest

stages:
  - test
  - build

cache:
  paths:
    - target/

test:
  stage: test
  only:
    - master
  script:
    - mvn test

build_image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: build
  only:
    - master
  when: manual
  script:
    - docker login -u $CI_USER -p $CI_PASSWORD
    - docker build -t $CI_IMAGE:$CI_TAG .
    - docker push $CI_IMAGE:$CI_TAG