image: maven:latest

stages:
  - test
  - build
  - push

cache:
  paths:
    - target/

test:
  stage: test
  only:
    - master
  script:
    - mvn test

build_image:
  image: docker:dind
  services:
    - docker:dind
  stage: build
  only:
    - master
  when: manual
  script:
    - docker login -u $CI_USER -p $CI_PASSWORD
    - docker build -t $CI_IMAGE:$CI_TAG .
    - docker push $CI_IMAGE:$CI_TAG

pushToHub:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: push
  tags: [pi]
  only:
    - master
  script:
    - sleep 10
    - docker login $HARBOR_BASEURL -u $HARBOR_USER -p $HARBOR_PASSWORD
    - docker pull  --platform linux/amd64 $CI_IMAGE:$CI_TAG
    - docker image tag $CI_IMAGE:$CI_TAG $HARBOR_URL
    - docker push $HARBOR_URL
  