image: maven:latest

stages:
  - test
  - build
  - push

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  DOCKER_TLS_CERTDIR: "/certs"
  MAVEN_SETTINGS_PATH: ".m2/settings.xml"

before_script:
  - mkdir .m2 || true
  - cp settings.xml .m2/settings.xml

cache:
  paths:
    - target/
    - .m2/repository

test:
  stage: test
  tags: [fujiitsu]
  only:
    - master
  script:
    - mvn test

build_image:
  image: docker:20.10.17-dind
  tags: [fujiitsu]
  variables: # not strictly needed, depending on runner configuration
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:20.10.17-dind
  stage: build
  only:
    - master
  when: manual
  script:
    - docker login $HARBOR_BASEURL -u $HARBOR_USER -p $HARBOR_PASSWORD
    - docker build -t $HARBOR_URL .
    - docker push $HARBOR_URL

pushToHub:
  needs:
    - build_image
  image: docker:dind
  services:
    - docker:dind
  stage: push
  tags: [pi]
  only:
    - master
  script:
    - docker login $HARBOR_BASEURL -u $HARBOR_USER -p $HARBOR_PASSWORD
    - docker login -u $CI_USER -p $CI_PASSWORD
    - docker pull  --platform linux/amd64 $HARBOR_BASEURL
    - docker image tag $HARBOR_BASEURL $CI_IMAGE:$CI_TAG
    - docker push $CI_IMAGE:$CI_TAG