version: '3'
services:
  smartOrganizrdb:
    image: mysql
    container_name: smartOrganizrdb
    restart: unless-stopped
    ports:
      - "3306:3306"
    #volumes:
    #  - ./data/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password #SQL root Passwort eingeben
      - MYSQL_PASSWORD=smartOrganizr #SQL Benutzer Passwort eingeben
      - MYSQL_DATABASE=smartOrganizr #Datenbank Name
      - MYSQL_USER=smartOrganizrUser #SQL Nutzername
      - MYSQL_INITDB_SKIP_TZINFO=1