version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
