version: '3'
services:
  smartOrganizrdb:
    image: mariadb
    container_name: smartOrganizrdb
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/smartOrganizr/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password #SQL root Passwort eingeben
      - MYSQL_PASSWORD=smartOrganizr #SQL Benutzer Passwort eingeben
      - MYSQL_DATABASE=smartOrganizr #Datenbank Name
      - MYSQL_USER=smartOrganizrUser #SQL Nutzername
      - MYSQL_INITDB_SKIP_TZINFO=1
    networks:
      - smartOrganizr

  smartOrganizr:
    depends_on:
      - smartOrganizrdb
    image: samuel19982/smartorganizr:latest
    container_name: smartOrganizr
    restart: unless-stopped
    ports:
      - "80:8080"
    networks:
      - smartOrganizr
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://smartOrganizrdb:3306/smartOrganizr
      - SPRING_DATASOURCE_USERNAME=smartOrganizr
      - SPRING_DATASOURCE_PASSWORD=smartOrganizr
      - ISSUER=<issuer-in- well-known/openid-configuration>
      - AUTH_URL=<url where your auth is done>
      - REALM=<keycloak-realm>
      - UI_URL=<your-frontend-resource>
      - ZIPKIN_URL=<zipkin-url> # Normally http://<your-ip>/api/v2/spans
networks:
  smartOrganizr:
    external: true
