FROM maven@sha256:d451510cd35ed056fceae676bfd54d2bdfc783283888f5853831e3082dad38b0 AS runtime


# Copy the package
COPY ./api/target/*-SNAPSHOT.jar \
	/app/smartOrganizr.jar

WORKDIR /app
ENTRYPOINT  ["java", "-jar","smartOrganizr.jar"]
EXPOSE 8080