version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    volumes:
      - .local/keycloak/:/opt/jboss/keycloak/standalone/data/
