FROM maven:3.9.3-amazoncorretto-20 AS runtime


# Copy the package
COPY ./api/target/*-SNAPSHOT.jar \
	/app/smartOrganizr.jar

WORKDIR /app
ENTRYPOINT  ["java", "-jar","smartOrganizr.jar"]
EXPOSE 8080