version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_LOG_LEVEL=ALL
    command:
      - start-dev
    volumes:
      - .local/keycloak/:/opt/jboss/keycloak/standalone/data/
