springdoc:
  api-docs:
    path: /api-docs
spring:
  config:
    import: optional:file:config.yml
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer}
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${zipking-url}



logging:
  pattern:
    level: \t [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

