// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Author struct {
	ID               string
	ExtraInformation sql.NullString
	Name             sql.NullString
	UserIDFk         sql.NullString
}

type AuthorsSeq struct {
	NextVal sql.NullInt64
}

type Concert struct {
	ID          string
	Description sql.NullString
	DueDate     sql.NullTime
	Hints       sql.NullString
	Location    sql.NullString
	Title       sql.NullString
	UserIDFk    sql.NullString
}

type Element struct {
	Type          string
	ID            string
	CreationDate  sql.NullTime
	Description   sql.NullString
	Name          sql.NullString
	NumberOfPages sql.NullInt32
	Title         sql.NullString
	UserIDFk      sql.NullString
	Parent        sql.NullString
	AuthorIDFk    sql.NullString
	PdfContent    sql.NullString
}

type NoteInConcert struct {
	ConcertIDFk    string
	NoteIDFk       string
	PlaceInConcert sql.NullInt32
}

type User struct {
	ID               string
	SelectedTheme    sql.NullString
	SideBarCollapsed bool
	Username         sql.NullString
}
