// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ClubParticipantRole string

const (
	ClubParticipantRoleLEITER         ClubParticipantRole = "LEITER"
	ClubParticipantRoleCOLEITER       ClubParticipantRole = "CO_LEITER"
	ClubParticipantRoleSCHRIFTFUEHRER ClubParticipantRole = "SCHRIFTFUEHRER"
	ClubParticipantRoleSCHATZMEISTER  ClubParticipantRole = "SCHATZMEISTER"
	ClubParticipantRoleMITGLIED       ClubParticipantRole = "MITGLIED"
)

func (e *ClubParticipantRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClubParticipantRole(s)
	case string:
		*e = ClubParticipantRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ClubParticipantRole: %T", src)
	}
	return nil
}

type NullClubParticipantRole struct {
	ClubParticipantRole ClubParticipantRole
	Valid               bool // Valid is true if ClubParticipantRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClubParticipantRole) Scan(value interface{}) error {
	if value == nil {
		ns.ClubParticipantRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClubParticipantRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClubParticipantRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClubParticipantRole), nil
}

type InventorySightingMatchedVia string

const (
	InventorySightingMatchedViaOCR    InventorySightingMatchedVia = "OCR"
	InventorySightingMatchedViaAI     InventorySightingMatchedVia = "AI"
	InventorySightingMatchedViaMANUAL InventorySightingMatchedVia = "MANUAL"
)

func (e *InventorySightingMatchedVia) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventorySightingMatchedVia(s)
	case string:
		*e = InventorySightingMatchedVia(s)
	default:
		return fmt.Errorf("unsupported scan type for InventorySightingMatchedVia: %T", src)
	}
	return nil
}

type NullInventorySightingMatchedVia struct {
	InventorySightingMatchedVia InventorySightingMatchedVia
	Valid                       bool // Valid is true if InventorySightingMatchedVia is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventorySightingMatchedVia) Scan(value interface{}) error {
	if value == nil {
		ns.InventorySightingMatchedVia, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventorySightingMatchedVia.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventorySightingMatchedVia) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventorySightingMatchedVia), nil
}

type Address struct {
	ID          string
	Street      string
	HouseNumber string
	Location    string
	PostalCode  string
	Country     string
}

type AiChatMessage struct {
	ID        int64
	SessionFk string
	Role      string
	Content   string
	CreatedAt time.Time
}

type AiChatSession struct {
	ID        string
	UserFk    string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Author struct {
	ID               string
	ExtraInformation sql.NullString
	Name             sql.NullString
	UserIDFk         sql.NullString
	WikidataID       sql.NullString
	BirthYear        sql.NullInt16
	DeathYear        sql.NullInt16
}

type Club struct {
	ID                        string
	Name                      string
	AddressID                 string
	ClubType                  string
	DatesVisibleForAllMembers bool
	MembersCanSendMessages    bool
	FeedbackVisibility        string
	ReasonVisibility          string
	ConfirmedRepresentative   bool
}

type ClubChat struct {
	ID        string
	ClubID    string
	UserAID   string
	UserBID   string
	CreatedAt time.Time
}

type ClubChatMessage struct {
	ID           string
	ChatID       string
	SenderUserID string
	Content      string
	CreatedAt    time.Time
}

type ClubChatRead struct {
	ChatID     string
	UserID     string
	LastReadAt time.Time
}

type ClubEvent struct {
	ID              string
	ClubID          string
	Summary         string
	Description     sql.NullString
	Location        sql.NullString
	GeoDateX        sql.NullFloat64
	GeoDateY        sql.NullFloat64
	EventType       string
	StartDate       time.Time
	EndDate         sql.NullTime
	Cancelled       bool
	CreatedByUserID string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ClubEventResponse struct {
	EventID     string
	UserID      string
	Status      string
	Reason      sql.NullString
	RespondedAt time.Time
}

type ClubFile struct {
	ID               string
	ClubID           string
	Name             string
	MimeType         string
	SizeBytes        int64
	Content          []byte
	UploadedByUserID string
	CreatedAt        time.Time
}

type ClubInvitation struct {
	Token           string
	ClubID          string
	InvitedEmail    string
	InvitedByUserID string
	CreatedAt       time.Time
	ExpiresAt       time.Time
	AcceptedAt      sql.NullTime
}

type ClubParticipant struct {
	UserID     string
	ClubID     string
	Role       ClubParticipantRole
	Authorized bool
}

type ClubPinboardPost struct {
	ID           string
	ClubID       string
	AuthorUserID string
	Title        string
	Body         string
	Pinned       bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Concert struct {
	ID          string
	DueDate     sql.NullTime
	Hints       sql.NullString
	Location    sql.NullString
	Title       sql.NullString
	UserIDFk    sql.NullString
	Description sql.NullString
}

type Element struct {
	Type            string
	ID              string
	CreationDate    sql.NullTime
	Name            sql.NullString
	NumberOfPages   sql.NullInt32
	UserIDFk        sql.NullString
	Parent          sql.NullString
	PdfContent      sql.NullString
	WikidataID      sql.NullString
	CompositionYear sql.NullInt16
	Genre           sql.NullString
	ComposerIDFk    sql.NullString
	ArrangerIDFk    sql.NullString
	Description     sql.NullString
	InventoryNo     sql.NullInt32
}

type Event struct {
	Uid         string
	UserIDFk    string
	Summary     sql.NullString
	Url         sql.NullString
	GeoDateX    sql.NullFloat64
	GeoDateY    sql.NullFloat64
	Location    sql.NullString
	TzID        sql.NullString
	Description sql.NullString
	StartDate   sql.NullTime
	EndDate     sql.NullTime
}

type IcalSync struct {
	ID         string
	UserIDFk   string
	IcalUrl    string
	Type       string
	LastSynced sql.NullTime
}

type InventorySighting struct {
	SweepFk    string
	NoteFk     string
	MatchedVia InventorySightingMatchedVia
	Confidence sql.NullInt16
	Incomplete bool
	CreatedAt  time.Time
}

type InventorySweep struct {
	ID          string
	FolderFk    string
	UserFk      string
	StartedAt   time.Time
	CompletedAt sql.NullTime
}

type MappeTag struct {
	TagID     string
	FolderFk  string
	UserFk    string
	CreatedAt time.Time
}

type NoteInConcert struct {
	ConcertIDFk    string
	NoteIDFk       string
	PlaceInConcert sql.NullInt32
}

type User struct {
	ID               string
	SideBarCollapsed bool
	Username         sql.NullString
	ProfilePicture   sql.NullString
	Email            sql.NullString
	Firstname        sql.NullString
	Lastname         sql.NullString
	Telephonenumber  sql.NullString
	Birthday         sql.NullTime
	Country          sql.NullString
	Postalcode       sql.NullString
	City             sql.NullString
	Street           sql.NullString
	IcalFeedToken    sql.NullString
}
