// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createAuthor = `-- name: CreateAuthor :execlastid
INSERT INTO authors (name, extra_information, user_id_fk) VALUES (?, ?, ?)
`

type CreateAuthorParams struct {
	Name             sql.NullString
	ExtraInformation sql.NullString
	UserIDFk         sql.NullString
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAuthor, arg.Name, arg.ExtraInformation, arg.UserIDFk)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors WHERE id = ? AND user_id_fk = ?
`

type DeleteAuthorParams struct {
	ID       int32
	UserIDFk sql.NullString
}

func (q *Queries) DeleteAuthor(ctx context.Context, arg DeleteAuthorParams) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, arg.ID, arg.UserIDFk)
	return err
}

const findAllAuthorsByCreatorAndSearchText = `-- name: FindAllAuthorsByCreatorAndSearchText :many
SELECT a.id, a.extra_information, a.name, a.user_id_fk
FROM authors a
         JOIN user c ON a.user_id_fk = c.user_id
WHERE c.user_id = ?
  AND (a.name LIKE CONCAT('%', ?, '%')
    OR a.extra_information LIKE CONCAT('%', ?, '%'))
`

type FindAllAuthorsByCreatorAndSearchTextParams struct {
	UserID   string
	CONCAT   interface{}
	CONCAT_2 interface{}
}

func (q *Queries) FindAllAuthorsByCreatorAndSearchText(ctx context.Context, arg FindAllAuthorsByCreatorAndSearchTextParams) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, findAllAuthorsByCreatorAndSearchText, arg.UserID, arg.CONCAT, arg.CONCAT_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.ExtraInformation,
			&i.Name,
			&i.UserIDFk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllAuthorsByCreatorUnpaged = `-- name: FindAllAuthorsByCreatorUnpaged :many
SELECT id, extra_information, name, user_id_fk FROM authors WHERE user_id_fk = ? ORDER BY name
`

func (q *Queries) FindAllAuthorsByCreatorUnpaged(ctx context.Context, userIDFk sql.NullString) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, findAllAuthorsByCreatorUnpaged, userIDFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.ExtraInformation,
			&i.Name,
			&i.UserIDFk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllByCreator = `-- name: FindAllByCreator :many
SELECT id, extra_information, name, user_id_fk FROM authors
WHERE user_id_fk = ? ORDER BY name LIMIT ? OFFSET ?
`

type FindAllByCreatorParams struct {
	UserIDFk sql.NullString
	Limit    int32
	Offset   int32
}

func (q *Queries) FindAllByCreator(ctx context.Context, arg FindAllByCreatorParams) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, findAllByCreator, arg.UserIDFk, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.ExtraInformation,
			&i.Name,
			&i.UserIDFk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllNotesByAuthor = `-- name: FindAllNotesByAuthor :many
SELECT type, id, creation_date, description, name, number_of_pages, title, user_id_fk, parent, author_id_fk, pdf_content, pdf_available FROM elements WHERE type ='note' AND author_id_fk = ? AND user_id_fk = ? ORDER BY title
`

type FindAllNotesByAuthorParams struct {
	AuthorIDFk sql.NullInt32
	UserIDFk   sql.NullString
}

func (q *Queries) FindAllNotesByAuthor(ctx context.Context, arg FindAllNotesByAuthorParams) ([]Element, error) {
	rows, err := q.db.QueryContext(ctx, findAllNotesByAuthor, arg.AuthorIDFk, arg.UserIDFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Element
	for rows.Next() {
		var i Element
		if err := rows.Scan(
			&i.Type,
			&i.ID,
			&i.CreationDate,
			&i.Description,
			&i.Name,
			&i.NumberOfPages,
			&i.Title,
			&i.UserIDFk,
			&i.Parent,
			&i.AuthorIDFk,
			&i.PdfContent,
			&i.PdfAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAuthorById = `-- name: FindAuthorById :one
SELECT id, extra_information, name, user_id_fk FROM authors WHERE id = ? and user_id_fk = ?
`

type FindAuthorByIdParams struct {
	ID       int32
	UserIDFk sql.NullString
}

func (q *Queries) FindAuthorById(ctx context.Context, arg FindAuthorByIdParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, findAuthorById, arg.ID, arg.UserIDFk)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.ExtraInformation,
		&i.Name,
		&i.UserIDFk,
	)
	return i, err
}

const findConcertById = `-- name: FindConcertById :one
SELECT id, description, due_date, hints, location, title, user_id_fk FROM concert WHERE id = ?
`

func (q *Queries) FindConcertById(ctx context.Context, id string) (Concert, error) {
	row := q.db.QueryRowContext(ctx, findConcertById, id)
	var i Concert
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DueDate,
		&i.Hints,
		&i.Location,
		&i.Title,
		&i.UserIDFk,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT user_id, selected_theme, side_bar_collapsed, username FROM user WHERE user_id = ?
`

func (q *Queries) FindUserById(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.SelectedTheme,
		&i.SideBarCollapsed,
		&i.Username,
	)
	return i, err
}

const getIndexAuthorsOnPage = `-- name: GetIndexAuthorsOnPage :many
SELECT COUNT(*) FROM authors a WHERE a.name<? ORDER BY a.name,a.id
`

func (q *Queries) GetIndexAuthorsOnPage(ctx context.Context, name sql.NullString) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getIndexAuthorsOnPage, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var count int64
		if err := rows.Scan(&count); err != nil {
			return nil, err
		}
		items = append(items, count)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :exec
UPDATE authors SET name = ?, extra_information = ? WHERE id = ?
`

type UpdateAuthorParams struct {
	Name             sql.NullString
	ExtraInformation sql.NullString
	ID               int32
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthor, arg.Name, arg.ExtraInformation, arg.ID)
	return err
}
