apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  MARIADB_DB_NAME: "smartOrganizrDB"
  MARIADB_USERNAME: "smartOrganizrUser"
  MARIADB_PASSWORD: "smartOrganizr"
  MARIADB_ROOT_PASSWORD: "smartOrganizrRoot"
