apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KEYCLOAK_REALM: <your-realm>
  ISSUER: <issuer-in- well-known/openid-configuration>
  AUTH_URL: <url where your auth is done>
  UI_URL: <ui client id>
