apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartorganizr
  labels:
    app: smartorganizr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartorganizr
  template:
    metadata:
      labels:
        app: smartorganizr
    spec:
      containers:
        - name: smartorganizr
          image: samuel19982/smartorganizr:latest
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mariadb-service:3306/smartOrganizrDB"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_PASSWORD
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_AUTH_SERVER_URL
            - name: KEYCLOAK_CREDENTIALS_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_CREDENTIALS_SECRET
            - name: KEYCLOAK_SSL_REQUIRED
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_SSL_REQUIRED
            - name: KEYCLOAK_RESOURCE
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_RESOURCE
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: smartorganizr
spec:
  selector:
    app: smartorganizr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartorganizr-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  ingressClassName: public
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smartorganizr
                port:
                  number: 80
