export const PUBLIC_CONFIG_KEY = "PUBLIC_CONFIG_KEY";
export const LOGIN_URL = "PUBLIC_URL"
export const ACCESS_TOKEN = "ACCESS_TOKEN"
export const REFRESH_TOKEN = "REFRESH_TOKEN"
export const ACCESS_TOKEN_EXPIRES_AT = "ACCESS_TOKEN_EXPIRES_AT"
export const NOTES_CACHE_KEY = "NOTES_CACHE_KEY"
export const NOTES_CACHE_UPDATED_AT = "NOTES_CACHE_UPDATED_AT"
export const FOLDERS_CACHE_KEY = "FOLDERS_CACHE_KEY"
export const FOLDERS_CACHE_UPDATED_AT = "FOLDERS_CACHE_UPDATED_AT"

